export type SiteConfValueType = 'string' | 'number' | 'boolean' | 'json';

export type SiteConfDefault = {
  key: string;
  envKey?: string;
  valueType: SiteConfValueType;
  category: string;
  description: string;
  defaultValue?: string;
  sensitive?: boolean;
  runtimeEditable?: boolean;
  validation?: Record<string, any>;
};

export const SITE_CONF_DEFAULTS: SiteConfDefault[] = [
  { key: 'frontend.logs.socket_url', valueType: 'string', category: 'frontend', description: '前端日志 Socket.IO 服务地址；留空时使用当前页面同源地址', defaultValue: '' },
  { key: 'monitoring.requests.jenkins_approval_token', valueType: 'string', category: 'monitoring', description: 'Jenkins 调用监控审批授权接口的共享令牌', defaultValue: '', sensitive: true },
  { key: 'monitoring.requests.jenkins.enabled', valueType: 'boolean', category: 'monitoring', description: '是否允许 Dashboard 触发受控 Jenkins 监控资源执行', defaultValue: 'false' },
  { key: 'monitoring.requests.jenkins.base_url', valueType: 'string', category: 'monitoring', description: '固定 Jenkins 服务地址（仅后端使用）', defaultValue: '' },
  { key: 'monitoring.requests.jenkins.username', valueType: 'string', category: 'monitoring', description: 'Jenkins API 用户名（仅后端使用）', defaultValue: '', sensitive: true },
  { key: 'monitoring.requests.jenkins.api_token', valueType: 'string', category: 'monitoring', description: 'Jenkins API Token（仅后端使用）', defaultValue: '', sensitive: true },
  { key: 'monitoring.requests.jenkins.job_name', valueType: 'string', category: 'monitoring', description: '受控 Jenkins Job 名称；仅允许 platform-bootstrap-hash', defaultValue: 'platform-bootstrap-hash', runtimeEditable: false },
  { key: 'monitoring.requests.jenkins.timeout_ms', valueType: 'number', category: 'monitoring', description: 'Dashboard 调用 Jenkins 的 HTTP 超时（毫秒）', defaultValue: '15000', validation: { min: 1000, max: 60000 } },
  { key: 'monitoring.requests.executors.hash-jenkins.enabled', valueType: 'boolean', category: 'monitoring', description: '是否启用 hashex 独立 Jenkins 执行器', defaultValue: 'false' },
  { key: 'monitoring.requests.executors.hash-jenkins.base_url', valueType: 'string', category: 'monitoring', description: 'hashex Jenkins 服务地址（仅后端使用）', defaultValue: '' },
  { key: 'monitoring.requests.executors.hash-jenkins.username', valueType: 'string', category: 'monitoring', description: 'hashex Jenkins API 用户名（仅后端使用）', defaultValue: '', sensitive: true },
  { key: 'monitoring.requests.executors.hash-jenkins.api_token', valueType: 'string', category: 'monitoring', description: 'hashex Jenkins API Token（仅后端使用）', defaultValue: '', sensitive: true },
  { key: 'monitoring.requests.executors.hash-jenkins.job_name', valueType: 'string', category: 'monitoring', description: 'hashex 监控资源受控 Jenkins Job', defaultValue: 'platform-bootstrap-hash', runtimeEditable: false },
  { key: 'monitoring.requests.executors.hash-jenkins.timeout_ms', valueType: 'number', category: 'monitoring', description: 'Dashboard 调用 hashex Jenkins 的 HTTP 超时（毫秒）', defaultValue: '15000', validation: { min: 1000, max: 60000 } },
  { key: 'cicd.executors.hash-jenkins.base_url', envKey: 'CICD_HASH_JENKINS_BASE_URL', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 Hash Jenkins 地址', defaultValue: '' },
  { key: 'cicd.executors.hash-jenkins.username', envKey: 'CICD_HASH_JENKINS_USERNAME', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 Hash Jenkins 机器账号', defaultValue: '', sensitive: true },
  { key: 'cicd.executors.hash-jenkins.api_token', envKey: 'CICD_HASH_JENKINS_API_TOKEN', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 Hash Jenkins API Token', defaultValue: '', sensitive: true },
  { key: 'cicd.executors.hash-jenkins.timeout_ms', envKey: 'CICD_HASH_JENKINS_TIMEOUT_MS', valueType: 'number', category: 'cicd', description: 'Hash Jenkins 只读诊断超时（毫秒）', defaultValue: '15000', validation: { min: 1000, max: 60000 } },
  { key: 'cicd.executors.mgbx-jenkins.base_url', envKey: 'CICD_MGBX_JENKINS_BASE_URL', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 MGBX Jenkins 地址', defaultValue: '' },
  { key: 'cicd.executors.mgbx-jenkins.username', envKey: 'CICD_MGBX_JENKINS_USERNAME', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 MGBX Jenkins 机器账号', defaultValue: '', sensitive: true },
  { key: 'cicd.executors.mgbx-jenkins.api_token', envKey: 'CICD_MGBX_JENKINS_API_TOKEN', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 MGBX Jenkins API Token', defaultValue: '', sensitive: true },
  { key: 'cicd.executors.mgbx-jenkins.timeout_ms', envKey: 'CICD_MGBX_JENKINS_TIMEOUT_MS', valueType: 'number', category: 'cicd', description: 'MGBX Jenkins 只读诊断超时（毫秒）', defaultValue: '15000', validation: { min: 1000, max: 60000 } },
  { key: 'cicd.executors.icoin-jenkins.base_url', envKey: 'CICD_ICOIN_JENKINS_BASE_URL', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 iCoin Jenkins 地址', defaultValue: '' },
  { key: 'cicd.executors.icoin-jenkins.username', envKey: 'CICD_ICOIN_JENKINS_USERNAME', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 iCoin Jenkins 机器账号', defaultValue: '', sensitive: true },
  { key: 'cicd.executors.icoin-jenkins.api_token', envKey: 'CICD_ICOIN_JENKINS_API_TOKEN', valueType: 'string', category: 'cicd', description: 'CI/CD 执行中心 iCoin Jenkins API Token', defaultValue: '', sensitive: true },
  { key: 'cicd.executors.icoin-jenkins.timeout_ms', envKey: 'CICD_ICOIN_JENKINS_TIMEOUT_MS', valueType: 'number', category: 'cicd', description: 'iCoin Jenkins 只读诊断超时（毫秒）', defaultValue: '15000', validation: { min: 1000, max: 60000 } },
  { key: 'monitoring.requests.gitlab.merge.enabled', valueType: 'boolean', category: 'monitoring', description: '是否启用审批后受控 GitLab 自动合并；默认关闭，未启用时保持现有人工 MR 提交流程', defaultValue: 'false' },
  { key: 'monitoring.requests.gitlab.base_url', valueType: 'string', category: 'monitoring', description: 'GitLab API 根地址（例如 https://gitlab.example.com/api/v4）', defaultValue: '' },
  { key: 'monitoring.requests.gitlab.project_id', valueType: 'string', category: 'monitoring', description: '受控 Kubernetes YAML GitLab 数值项目 ID', defaultValue: '' },
  { key: 'monitoring.requests.gitlab.bot_token', valueType: 'string', category: 'monitoring', description: 'Dashboard 专用 GitLab Bot API Token；仅用于读取和合并绑定 MR', defaultValue: '', sensitive: true },
  { key: 'monitoring.requests.gitlab.target_branch', valueType: 'string', category: 'monitoring', description: '受控 GitLab MR 目标分支；仅允许 hash-jenkins', defaultValue: 'hash-jenkins', runtimeEditable: false },
  { key: 'monitoring.requests.gitlab.timeout_ms', valueType: 'number', category: 'monitoring', description: 'Dashboard 调用 GitLab API 的 HTTP 超时（毫秒）', defaultValue: '15000', validation: { min: 1000, max: 60000 } },
  { key: 'line.inventory_probe.api_url', envKey: 'LINE_INVENTORY_PROBE_API_URL', valueType: 'string', category: 'line', description: '线路总览探测聚合接口地址', defaultValue: '' },
  { key: 'line.availability.window_ms', envKey: 'LINE_AVAILABILITY_WINDOW_MS', valueType: 'number', category: 'line', description: '线路可用性判定时间窗（毫秒）', defaultValue: '120000', validation: { min: 1000 } },
  { key: 'line.availability.cache_ttl_ms', envKey: 'LINE_AVAILABILITY_CACHE_TTL_MS', valueType: 'number', category: 'line', description: '线路探测快照缓存 TTL（毫秒）', defaultValue: '15000', validation: { min: 0 } },
  { key: 'line.availability.http_timeout_ms', envKey: 'LINE_AVAILABILITY_HTTP_TIMEOUT_MS', valueType: 'number', category: 'line', description: '线路探测聚合接口 HTTP 超时（毫秒）', defaultValue: '3000', validation: { min: 1000 } },
  { key: 'line.availability.up_threshold', envKey: 'LINE_AVAILABILITY_UP_THRESHOLD', valueType: 'number', category: 'line', description: '线路可用判定阈值，支持 0~1 或 0~100', defaultValue: '0.8', validation: { min: 0, max: 100 } },
  { key: 'line.provider.cache_ttl_ms', envKey: 'LINE_PROVIDER_CACHE_TTL_MS', valueType: 'number', category: 'line', description: '线路 provider 识别缓存 TTL（毫秒）', defaultValue: '3600000', validation: { min: 0 } },
  { key: 'line.provider.rules_json', envKey: 'LINE_PROVIDER_RULES_JSON', valueType: 'json', category: 'line', description: '线路 provider 规则扩展（JSON 数组）', defaultValue: '[]' },
  { key: 'line.ssl.cache_ttl_ms', envKey: 'LINE_SSL_CACHE_TTL_MS', valueType: 'number', category: 'line', description: '线路证书聚合缓存 TTL（毫秒）', defaultValue: '300000', validation: { min: 0 } },
  { key: 'line.ssl.tls_timeout_ms', envKey: 'LINE_SSL_TLS_TIMEOUT_MS', valueType: 'number', category: 'line', description: 'TLS 证书探测超时（毫秒）', defaultValue: '5000', validation: { min: 1000 } },
  { key: 'line.ssl.resolve_concurrency', envKey: 'LINE_SSL_RESOLVE_CONCURRENCY', valueType: 'number', category: 'line', description: '线路证书并发探测数量', defaultValue: '8', validation: { min: 1, max: 100 } },

  { key: 'aiops.llm.provider', envKey: 'AIOPS_LLM_PROVIDER', valueType: 'string', category: 'aiops', description: 'AI Ops LLM provider（当前仅支持 openclaw）', defaultValue: 'openclaw', validation: { enum: ['openclaw'] } },
  { key: 'aiops.openclaw.base_url', envKey: 'AIOPS_OPENCLAW_BASE_URL', valueType: 'string', category: 'aiops', description: 'AI Ops OpenClaw OpenAI-compatible API Base URL', defaultValue: '' },
  { key: 'aiops.openclaw.model', envKey: 'AIOPS_OPENCLAW_MODEL', valueType: 'string', category: 'aiops', description: 'AI Ops OpenClaw 模型名', defaultValue: 'openclaw/default' },
  { key: 'aiops.openclaw.token', envKey: 'AIOPS_OPENCLAW_TOKEN', valueType: 'string', category: 'aiops', description: 'AI Ops OpenClaw API Token', defaultValue: '', sensitive: true },
  { key: 'aiops.nl2sql.fewshot_cases_path', envKey: 'AIOPS_NL2SQL_FEWSHOT_CASES_PATH', valueType: 'string', category: 'aiops', description: 'NL2SQL few-shot CSV 文件路径；为空时自动探测默认路径', defaultValue: '' },
  { key: 'aiops.openclaw.timeout_ms', envKey: 'AIOPS_OPENCLAW_TIMEOUT_MS', valueType: 'number', category: 'aiops', description: 'OpenClaw chat/completions 请求超时（毫秒）', defaultValue: '20000', validation: { min: 1000 } },
  { key: 'aiops.nl2sql.fewshot_max_cases', envKey: 'AIOPS_NL2SQL_FEWSHOT_MAX_CASES', valueType: 'number', category: 'aiops', description: '每次注入到 NL2SQL 提示词中的 few-shot 样例数量', defaultValue: '6', validation: { min: 0, max: 50 } },
  { key: 'aiops.sql.whitelist_tables', envKey: 'AIOPS_SQL_WHITELIST_TABLES', valueType: 'string', category: 'aiops', description: 'AI Ops SQL 全局兜底表白名单，逗号分隔；环境级 database.aiops 优先', defaultValue: '' },
  { key: 'aiops.sql.whitelist_databases', envKey: 'AIOPS_SQL_WHITELIST_DATABASES', valueType: 'string', category: 'aiops', description: 'AI Ops SQL 全局兜底数据库白名单，逗号分隔；环境级 database.aiops 优先', defaultValue: '' },
  { key: 'aiops.sql.default_limit', envKey: 'AIOPS_SQL_DEFAULT_LIMIT', valueType: 'number', category: 'aiops', description: 'AI Ops SQL 默认 LIMIT', defaultValue: '200', validation: { min: 1 } },
  { key: 'aiops.sql.max_limit', envKey: 'AIOPS_SQL_MAX_LIMIT', valueType: 'number', category: 'aiops', description: 'AI Ops SQL 最大 LIMIT', defaultValue: '1000', validation: { min: 1 } },
  { key: 'aiops.sql.timeout_ms', envKey: 'AIOPS_SQL_TIMEOUT_MS', valueType: 'number', category: 'aiops', description: 'AI Ops SQL 查询超时（毫秒）', defaultValue: '5000', validation: { min: 1000 } },

  { key: 'query_center.agent.k8s_namespace', envKey: 'QUERY_CENTER_AGENT_K8S_NAMESPACE', valueType: 'string', category: 'query-center', description: 'Query Center Agent Kubernetes namespace', defaultValue: 'default' },
  { key: 'query_center.agent.k8s_service', envKey: 'QUERY_CENTER_AGENT_K8S_SERVICE', valueType: 'string', category: 'query-center', description: 'Query Center Agent Kubernetes service name', defaultValue: 'dashboard-db-gateway-agent' },
  { key: 'query_center.agent.k8s_port', envKey: 'QUERY_CENTER_AGENT_K8S_PORT', valueType: 'number', category: 'query-center', description: 'Query Center Agent Kubernetes service port', defaultValue: '8080', validation: { min: 1, max: 65535 } },
  { key: 'query_center.agent.token', envKey: 'QUERY_CENTER_AGENT_TOKEN', valueType: 'string', category: 'query-center', description: 'Query Center Agent Shared Token', defaultValue: '', sensitive: true },
  { key: 'query_center.gateway.enabled', envKey: 'QUERY_CENTER_GATEWAY_ENABLED', valueType: 'boolean', category: 'query-center', description: '查询中心网关是否启用', defaultValue: 'false' },
  { key: 'query_center.gateway.timeout_ms', envKey: 'QUERY_CENTER_GATEWAY_TIMEOUT_MS', valueType: 'number', category: 'query-center', description: '查询中心网关请求超时（毫秒）', defaultValue: '15000', validation: { min: 1000 } },
  { key: 'query_center.gateway.env_allowlist', envKey: 'QUERY_CENTER_GATEWAY_ENV_ALLOWLIST', valueType: 'string', category: 'query-center', description: '允许走网关的环境 ID，逗号分隔；为空表示不限制', defaultValue: '' },
  { key: 'query_center.gateway.env_denylist', envKey: 'QUERY_CENTER_GATEWAY_ENV_DENYLIST', valueType: 'string', category: 'query-center', description: '禁止走网关的环境 ID，逗号分隔', defaultValue: '' },
  { key: 'query_center.gateway.transport', envKey: 'QUERY_CENTER_GATEWAY_TRANSPORT', valueType: 'string', category: 'query-center', description: '查询中心网关传输模式：k8s-proxy 或 direct-url', defaultValue: 'k8s-proxy', validation: { enum: ['k8s-proxy', 'direct-url'] } },

  { key: 'oncall.alertmanager.bearer_token', envKey: 'ONCALL_ALERTMANAGER_BEARER_TOKEN', valueType: 'string', category: 'oncall', description: 'Alertmanager 调用 Dashboard Webhook 的 Bearer Token', defaultValue: '', sensitive: true },
  { key: 'oncall.lark.webhook_url', envKey: 'ONCALL_LARK_WEBHOOK_URL', valueType: 'string', category: 'oncall', description: 'Oncall Lark Custom Bot Webhook 备用地址', defaultValue: '', sensitive: true },
  { key: 'oncall.lark.chat_id', envKey: 'ONCALL_LARK_CHAT_ID', valueType: 'string', category: 'oncall', description: 'Hotline App 应急群 chat_id', defaultValue: '', sensitive: true },
  { key: 'oncall.default_environment', envKey: 'ONCALL_DEFAULT_ENVIRONMENT', valueType: 'string', category: 'oncall', description: '告警缺少 environment 标签时使用的默认环境', defaultValue: 'mgbx' },
  { key: 'oncall.webhook.allow_insecure', envKey: 'ONCALL_ALLOW_INSECURE_WEBHOOK', valueType: 'boolean', category: 'oncall', description: '是否允许 Alertmanager Webhook 在没有 Token 时继续接收；生产环境必须关闭', defaultValue: 'false' },
  { key: 'oncall.hotline.lark_app_id', envKey: 'HOTLINE_LARK_APP_ID', valueType: 'string', category: 'oncall', description: 'Hotline App ID', defaultValue: '', sensitive: true },
  { key: 'oncall.hotline.lark_app_secret', envKey: 'HOTLINE_LARK_APP_SECRET', valueType: 'string', category: 'oncall', description: 'Hotline App Secret', defaultValue: '', sensitive: true },
  { key: 'oncall.hotline.enabled', envKey: 'HOTLINE_ENABLED', valueType: 'boolean', category: 'oncall', description: '是否启用 Hotline 电话加急', defaultValue: 'false' },
  { key: 'oncall.hotline.urgent_phone_supported', envKey: 'HOTLINE_URGENT_PHONE_SUPPORTED', valueType: 'boolean', category: 'oncall', description: '当前 Lark 租户是否支持应用电话加急', defaultValue: 'false' },
  { key: 'oncall.escalation.enabled', envKey: 'ONCALL_ESCALATION_ENABLED', valueType: 'boolean', category: 'oncall', description: '是否启用 Oncall 自动升级调度', defaultValue: 'false' },
  { key: 'oncall.escalation.l1_ack_timeout_minutes', envKey: 'ONCALL_L1_ACK_TIMEOUT_MINUTES', valueType: 'number', category: 'oncall', description: 'L1 ACK 超时时间（分钟）', defaultValue: '10', validation: { min: 1, max: 1440 } },
  { key: 'oncall.escalation.l2_ack_timeout_minutes', envKey: 'ONCALL_L2_ACK_TIMEOUT_MINUTES', valueType: 'number', category: 'oncall', description: 'L2 ACK 超时时间（分钟）', defaultValue: '5', validation: { min: 1, max: 1440 } },
  { key: 'oncall.escalation.owner_ack_timeout_minutes', envKey: 'ONCALL_OWNER_ACK_TIMEOUT_MINUTES', valueType: 'number', category: 'oncall', description: '负责人 ACK 超时时间（分钟）', defaultValue: '5', validation: { min: 1, max: 1440 } },

  { key: 'cdn.aliyun.dcdn_endpoint', envKey: 'DCDN_ENDPOINT', valueType: 'string', category: 'cdn', description: '阿里云 DCDN API Endpoint', defaultValue: 'https://dcdn.aliyuncs.com' },
  { key: 'cdn.aliyun.dcdn.enabled', envKey: 'ALIYUN_DCDN_ENABLED', valueType: 'boolean', category: 'cdn', description: '是否启用阿里云 DCDN 域名同步', defaultValue: 'true' },
  { key: 'cdn.aliyun.dcdn.timeout_ms', envKey: 'ALIYUN_DCDN_TIMEOUT_MS', valueType: 'number', category: 'cdn', description: '阿里云 DCDN OpenAPI 请求超时（毫秒）', defaultValue: '15000', validation: { min: 1000 } },
  { key: 'cdn.aliyun.esa.enabled', envKey: 'ALIYUN_ESA_ENABLED', valueType: 'boolean', category: 'cdn', description: '是否启用阿里云 ESA 域名同步（当前仅占位）', defaultValue: 'false' },
  { key: 'cdn.aliyun.esa.endpoint', envKey: 'ALIYUN_ESA_ENDPOINT', valueType: 'string', category: 'cdn', description: '阿里云 ESA OpenAPI Endpoint（占位）', defaultValue: 'https://esa.cn-hangzhou.aliyuncs.com' },
  { key: 'cdn.aliyun.esa.timeout_ms', envKey: 'ALIYUN_ESA_TIMEOUT_MS', valueType: 'number', category: 'cdn', description: '阿里云 ESA OpenAPI 请求超时（毫秒，占位）', defaultValue: '15000', validation: { min: 1000 } },
  { key: 'cdn.aliyun.access_key_id', envKey: 'ALIYUN_ACCESS_KEY_ID', valueType: 'string', category: 'cdn', description: '阿里云 RAM AccessKey ID', defaultValue: '', sensitive: true },
  { key: 'cdn.aliyun.access_key_secret', envKey: 'ALIYUN_ACCESS_KEY_SECRET', valueType: 'string', category: 'cdn', description: '阿里云 RAM AccessKey Secret', defaultValue: '', sensitive: true },
  { key: 'cdn.wangsu.enabled', envKey: 'WANGSU_CDN_ENABLED', valueType: 'boolean', category: 'cdn', description: '是否启用网宿 CDN OpenAPI 集成', defaultValue: 'false' },
  { key: 'cdn.wangsu.endpoint', envKey: 'WANGSU_CDN_ENDPOINT', valueType: 'string', category: 'cdn', description: '网宿 CDN OpenAPI Endpoint', defaultValue: 'https://open.chinanetcenter.com' },
  { key: 'cdn.wangsu.username', envKey: 'WANGSU_CDN_USERNAME', valueType: 'string', category: 'cdn', description: '网宿 CDN OpenAPI 账号名 / username（用于 Basic Auth username）', defaultValue: '', sensitive: true },
  { key: 'cdn.wangsu.api_key', envKey: 'WANGSU_CDN_API_KEY', valueType: 'string', category: 'cdn', description: '网宿 CDN OpenAPI API Key（用于 HMAC-SHA1 Date 签名）', defaultValue: '', sensitive: true },
  { key: 'cdn.wangsu.access_key_id', envKey: 'WANGSU_CDN_ACCESS_KEY_ID', valueType: 'string', category: 'cdn', description: '网宿 CDN OpenAPI AccessKey ID（AKSK 鉴权优先使用）', defaultValue: '', sensitive: true },
  { key: 'cdn.wangsu.access_key_secret', envKey: 'WANGSU_CDN_ACCESS_KEY_SECRET', valueType: 'string', category: 'cdn', description: '网宿 CDN OpenAPI AccessKey Secret（AKSK 鉴权优先使用）', defaultValue: '', sensitive: true },
  { key: 'cdn.wangsu.timeout_ms', envKey: 'WANGSU_CDN_TIMEOUT_MS', valueType: 'number', category: 'cdn', description: '网宿 CDN OpenAPI 请求超时（毫秒）', defaultValue: '15000', validation: { min: 1000 } },

  { key: 'sso.keycloak.issuer', envKey: 'KEYCLOAK_ISSUER', valueType: 'string', category: 'sso', description: 'Keycloak issuer/realm 地址', defaultValue: '' },
  { key: 'sso.keycloak.client_id', envKey: 'KEYCLOAK_CLIENT_ID', valueType: 'string', category: 'sso', description: 'Keycloak Client ID', defaultValue: '' },
  { key: 'sso.keycloak.client_secret', envKey: 'KEYCLOAK_CLIENT_SECRET', valueType: 'string', category: 'sso', description: 'Keycloak Client Secret', defaultValue: '', sensitive: true },
  { key: 'sso.keycloak.redirect_uri', envKey: 'KEYCLOAK_REDIRECT_URI', valueType: 'string', category: 'sso', description: 'Keycloak 后端回调地址', defaultValue: '' },
  { key: 'sso.keycloak.redirect_uris', envKey: 'KEYCLOAK_REDIRECT_URIS', valueType: 'string', category: 'sso', description: 'Keycloak 允许的后端回调地址列表，逗号分隔', defaultValue: '' },
  { key: 'sso.frontend.redirect_uri', envKey: 'SSO_FRONTEND_REDIRECT_URI', valueType: 'string', category: 'sso', description: '登录成功后回到前端页面', defaultValue: 'http://localhost:5173/sso/callback' },
  { key: 'sso.frontend.redirect_uris', envKey: 'SSO_FRONTEND_REDIRECT_URIS', valueType: 'string', category: 'sso', description: '允许的前端回跳地址列表，逗号分隔', defaultValue: '' },
];

export const SITE_CONF_DEFAULTS_BY_KEY = new Map(SITE_CONF_DEFAULTS.map((item) => [item.key, item]));
