CREATE TABLE `site_monitors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `environment_id` varchar(64) NOT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `host` varchar(255) NOT NULL,
  `port` int(11) NOT NULL DEFAULT '443',
  `is_https` tinyint(1) NOT NULL DEFAULT '1',
  `environment_label` varchar(200) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `acceptable_status_codes` varchar(255) DEFAULT NULL,
  `last_checked_at` datetime DEFAULT NULL,
  `dns_ok` tinyint(1) DEFAULT NULL,
  `resolved_ips` text,
  `tcp_latency_ms` int(11) DEFAULT NULL,
  `http_status` int(11) DEFAULT NULL,
  `ssl_valid` tinyint(1) DEFAULT NULL,
  `ssl_issuer` varchar(255) DEFAULT NULL,
  `ssl_subject` varchar(255) DEFAULT NULL,
  `ssl_not_before` datetime DEFAULT NULL,
  `ssl_not_after` datetime DEFAULT NULL,
  `last_error` text,
  `failure_count` int(11) NOT NULL DEFAULT '0',
  `last_ok_at` datetime DEFAULT NULL,
  `last_alert_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_env_host_port` (`environment_id`,`host`,`port`),
  KEY `idx_host_port` (`host`,`port`),
  KEY `idx_site_env` (`environment_id`),
  KEY `idx_site_tenant` (`environment_id`,`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=utf8mb4;